apiVersion: v1
kind: Secret
metadata:
  name: score-service-secret
type: Opaque
stringData:
  POSTGRES_DSN: "host=host.minikube.internal user=root password=root dbname=score port=54317 sslmode=disable"
  RABBIT_MQ_DSN: "amqp://admin:admin@host.minikube.internal:5672"