services:
  postgres17:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54317:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbit
    ports:
      - "5672:5672"  # MQ port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - ./.env

volumes:
  postgres17_data:
