services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: frontend.dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ../../frontend/.env:/app/.env
    depends_on:
      - broker
  broker:
    build:
      context: ../../broker
      dockerfile: broker.dockerfile
    container_name: broker
    ports:
      - "8081:80"
    volumes:
      - ../../broker/.env:/app/.env
    depends_on:
      - product-service
      - widget-service
      - rabbitmq
  product-service:
    build:
      context: ../../product-service
      dockerfile: product-service.dockerfile
    container_name: product-service
    ports:
      - "8082:80"
      - "8083:81"
    volumes:
      - ../../product-service/.env:/app/.env
    depends_on:
      - postgres17
  widget-service:
    build:
      context: ../../widget-service
      dockerfile: widget-service.dockerfile
    container_name: widget-service
    ports:
      - "8084:80"
      - "8085:81"
    volumes:
      - ../../widget-service/.env:/app/.env
    depends_on:
      - postgres17
  score-service:
    build:
      context: ../../score-service
      dockerfile: score-service.dockerfile
    container_name: score-service
    ports:
      - "8086:80"
      - "8087:81"
    volumes:
      - ../../score-service/.env:/app/.env
    depends_on:
      - postgres17
      - rabbitmq
  postgres17:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54317:5432"
    volumes:
      - postgres17_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    env_file:
      - ./.env
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  # MQ port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    env_file:
      - ./.env

volumes:
  postgres17_data:
