apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
stringData:
  POSTGRES_DSN: "host=host.minikube.internal user=root password=root dbname=product port=54317 sslmode=disable"
