apiVersion: v1
kind: Secret
metadata:
  name: widget-service-secret
type: Opaque
stringData:
  POSTGRES_PRODUCT_DSN: "host=host.minikube.internal user=root password=root dbname=product port=54317 sslmode=disable"
  POSTGRES_SCORE_DSN: "host=host.minikube.internal user=root password=root dbname=score port=54317 sslmode=disable"